server.port: 9093

server:
  error:
    include-stacktrace: never
    whitelabel:
      enabled: false
spring:
  datasource:
    postgres:
      url: jdbc:postgresql://10.6.0.13:5432/dev-app
      username: dev-app
      password: G10hrWmCYYNy98
      driverClassName: org.postgresql.Driver
    msql:
      url: jdbc:sqlserver://192.168.0.129:1433;database=tms
      username: devops
      password: devops
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      maximum-pool-size: 10
    tomcat:
      max-active: 10
#    msql:
#      url: jdbc:sqlserver://localhost:1433;database=TestDb;encrypt=false;trustServerCertificate=true
#      username: asmws
#      password: mypass1.
#      driverClassName: com.mysql.jdbc.Driver

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    enable:
      all: true
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true