server.port: 9091
spring:
  datasource:
    postgres:
      url: jdbc:postgresql://localhost:3723/accounts
      username: postgres
      password: postgres
      driverClassName: org.postgresql.Driver
    msql:
      url: jdbc:postgresql://localhost:3722/db_task
      username: postgres
      password: postgres
      driverClassName: org.postgresql.Driver
#    msql:
#      url: jdbc:sqlserver://localhost:1433;database=TestDb;encrypt=false;trustServerCertificate=true
#      username: asmws
#      password: mypass1.
#      driverClassName: com.mysql.jdbc.Driver
