version: "2"

services:
  postgresql:
    image: 'bitnami/postgresql:latest'
    ports:
      - '3723:5432'
    volumes:
      - 'postgresql_master_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=db_logk

volumes:
  postgresql_master_data: